language: go
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master
env:
  global:
    - COVERAGE_PATH=coverage/coverage.out
install: true
before_script:
  - mkdir ./coverage
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - sudo sh ./.travis.gogenerate.sh
  - sudo sh ./.travis.gofmt.sh
  - go test -v -race -coverprofile=$COVERAGE_PATH
after_success:
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=$COVERAGE_PATH -service=travis-ci
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
